// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA33S-phpWwa2aVLjzWeDJk9t9Stn9-7cg',
    appId: '1:826590992845:web:f5c343e12526b3b6074c84',
    messagingSenderId: '826590992845',
    projectId: 'fir-fcacc',
    authDomain: 'fir-fcacc.firebaseapp.com',
    storageBucket: 'fir-fcacc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQgsKRQLO4IbCad8FwHUtlRdCxRly348',
    appId: '1:826590992845:android:82e71abec2551d3e074c84',
    messagingSenderId: '826590992845',
    projectId: 'fir-fcacc',
    storageBucket: 'fir-fcacc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWcjup9oeqdy85qSV0hJlUMSK9oM7abm4',
    appId: '1:826590992845:ios:aef19c79040d98ac074c84',
    messagingSenderId: '826590992845',
    projectId: 'fir-fcacc',
    storageBucket: 'fir-fcacc.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
